# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-04 12:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemname',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 12, 32, 44, 28372, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemname',
            name='type',
            field=models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.CASCADE, related_name='types', to='items.ItemType'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 12, 32, 44, 27482, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='itemname',
            table='item_name',
        ),
        migrations.AlterModelTable(
            name='itemtype',
            table='item_type',
        ),
    ]
