# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-05 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20170804_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('deleted', models.IntegerField(choices=[(0, 'Not Deleted'), (1, 'Deleted')], default=0)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'db_table': 'items',
            },
            managers=[
                ('status', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ItemCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.CASCADE, to='items.ItemType')),
            ],
            options={
                'db_table': 'item_code',
            },
        ),
        migrations.RemoveField(
            model_name='itemname',
            name='type',
        ),
        migrations.DeleteModel(
            name='ItemName',
        ),
        migrations.AddField(
            model_name='item',
            name='code',
            field=models.ForeignKey(db_column='code', on_delete=django.db.models.deletion.CASCADE, related_name='item_code', to='items.ItemCode'),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.CASCADE, related_name='types', to='items.ItemType'),
        ),
    ]
