# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20170805_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='type',
            new_name='types',
        ),
    ]
