# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_auto_20170806_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_name', to='items.ItemType'),
        ),
    ]
