# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-04 12:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 8, 4, 12, 51, 59, 102580, tzinfo=utc))),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('status', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 8, 4, 12, 51, 59, 102580, tzinfo=utc))),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('deleted', models.IntegerField(choices=[(1, 'Not Deleted'), (0, 'Deleted')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='department',
            field=models.ForeignKey(db_column='department', on_delete=django.db.models.deletion.CASCADE, related_name='department_id', to='companies.Departments'),
        ),
    ]
